sonar.projectKey=statisticsnorway_kvakk-git-tools
sonar.organization=statisticsnorway
sonar.host.url=https://sonarcloud.io

sonar.sources=src/kvakk_git_tools/
sonar.tests=tests/

sonar.python.version=3.6
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
