name: Platforms
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  platforms:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-20.04
            python-version: "3.6"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run script
        run: |
          python kvakk_git_tools/ssb_gitconfig.py --test
